version: 0.2

phases:
  pre_build:
    commands:
      # Log in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      # Determine Git tag (or “latest”)
      - GIT_TAG=$(git describe --tags --exact-match || echo "latest")

  build:
    commands:
      - echo "Building Docker image from custom DockerFile"
      # Note the -f flag pointing at “DockerFile”
      - docker build \
          -f DockerFile \
          -t $ECR_REPO_NAME:latest \
          .

  post_build:
    commands:
      # Tag with Git tag & “latest”
      - docker tag $ECR_REPO_NAME:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$GIT_TAG
      - docker tag $ECR_REPO_NAME:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest

      # Push both tags
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$GIT_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
