FROM python:3.12-bullseye

# Expose the port the app runs on
EXPOSE 3000

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

ENTRYPOINT ["python"]

CMD ["main.py"]
